### PR TITLE
Peer caching

### PR DESCRIPTION
**Pull request by jerryblakley**

### CODE REVIEW

**Comment by nstielau** [comment]
@jerryblakley Are we going to deploy this in the next month?  If not, let's close it out.

**Comment by jerryblakley** [comment]
Peer caching is going to come back at some point. It would be nice to have at least this around to remember what we'll need to do. If we need to clean up, I'll capture the code in some fashion and keep it around.

**Comment by nstielau** [comment]
@jerryblakley  I'll close the PR and keep the branch up.

**Comment by nstielau** [comment]
Branch is at: https://github.com/pantheon-systems/fusedav/tree/peer-caching

**Pull request closed without merging**
